version: 2
updates:
  # Enable version updates for npm (works with pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"  # Replace with actual GitHub username
    assignees:
      - "your-github-username"  # Replace with actual GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    groups:
      # Group React-related packages
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      # Group Next.js related packages
      nextjs:
        patterns:
          - "next"
          - "next-*"
      # Group Radix UI packages
      radix-ui:
        patterns:
          - "@radix-ui/*"
      # Group AI SDK packages
      ai-sdk:
        patterns:
          - "@ai-sdk/*"
          - "ai"
      # Group testing packages
      testing:
        patterns:
          - "@playwright/*"
          - "@types/*"
      # Group development tools
      dev-tools:
        patterns:
          - "drizzle-*"
          - "@biomejs/*"
          - "eslint*"
          - "typescript"
          - "@types/*"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      # Ignore Next.js canary versions (unstable)
      - dependency-name: "next"
        versions: ["15.3.0-canary*"]

  # Backend Python dependencies (if applicable)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    groups:
      python-deps:
        patterns:
          - "*"